ALTER TABLE wcf1_clique
 ADD boardID int(10) NOT NULL DEFAULT 0,
 ADD boardEnable TINYINT (1) NOT NULL DEFAULT 0;

ALTER TABLE wcf1_clique_group_rights
 ADD canSeeBoards1 TINYINT(1) NOT NULL DEFAULT 0,
 ADD canSeeBoards2 TINYINT(1) NOT NULL DEFAULT 0,
 ADD canSeeBoards3 TINYINT(1) NOT NULL DEFAULT 0,
 ADD canSeeBoards4 TINYINT(1) NOT NULL DEFAULT 0,
 ADD canMakePosts1 TINYINT(1) NOT NULL DEFAULT 0,
 ADD canMakePosts2 TINYINT(1) NOT NULL DEFAULT 0,
 ADD canMakePosts3 TINYINT(1) NOT NULL DEFAULT 0,
 ADD canMakePosts4 TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE wbb1_1_board
 ADD cliquBoard tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
 ADD cliqueID INT(10) UNSIGNED NOT NULL DEFAULT 0;