DROP TABLE IF EXISTS wcf1_clique;
CREATE TABLE wcf1_clique (
 cliqueID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(255) NOT NULL DEFAULT '',
 time INT(10) NOT NULL DEFAULT 0,
 status TINYINT NOT NULL DEFAULT 0,
 commentEnable TINYINT NOT NULL DEFAULT 1,
 overviewEnable TINYINT NOT NULL DEFAULT 1,
 membershipEnable TINYINT NOT NULL DEFAULT 1,
 shortDescription TEXT,
 description MEDIUMTEXT,
 raiserID INT(10) NOT NULL,
 categorieID INT(10) NOT NULL,
 image VARCHAR(255) NOT NULL DEFAULT '',
 width SMALLINT(5) NOT NULL DEFAULT 0,
 height SMALLINT(5) NOT NULL DEFAULT 0,
 ratings smallint(5) NOT NULL DEFAULT '0',
 rating mediumint(7) NOT NULL DEFAULT '0',
 FULLTEXT KEY (name, shortDescription, description)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS wcf1_user_to_clique;
CREATE TABLE wcf1_user_to_clique (
 userID INT(10) NOT NULL DEFAULT 0,
 cliqueID INT(10) NOT NULL DEFAULT 0,
 groupType TINYINT(1) NOT NULL DEFAULT 0,
 enteredTime INT(10) NOT NULL DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS wcf1_clique_group_rights;
CREATE TABLE wcf1_clique_group_rights (
 cliqueID INT(10) NOT NULL DEFAULT 0,
 canEditClique1 TINYINT(1) NOT NULL DEFAULT 0,
 canEditClique2 TINYINT(1) NOT NULL DEFAULT 0,
 canEditClique3 TINYINT(1) NOT NULL DEFAULT 0,
 canEditClique4 TINYINT(1) NOT NULL DEFAULT 0,
 canDeleteClique1 TINYINT(1) NOT NULL DEFAULT 0,
 canDeleteClique2 TINYINT(1) NOT NULL DEFAULT 0,
 canDeleteClique3 TINYINT(1) NOT NULL DEFAULT 0,
 canDeleteClique4 TINYINT(1) NOT NULL DEFAULT 0,
 canEditRights1 TINYINT(1) NOT NULL DEFAULT 0,
 canEditRights2 TINYINT(1) NOT NULL DEFAULT 0,
 canEditRights3 TINYINT(1) NOT NULL DEFAULT 0,
 canEditRights4 TINYINT(1) NOT NULL DEFAULT 0,
 canInviteUsers1 TINYINT(1) NOT NULL DEFAULT 0,
 canInviteUsers2 TINYINT(1) NOT NULL DEFAULT 0,
 canInviteUsers3 TINYINT(1) NOT NULL DEFAULT 0,
 canInviteUsers4 TINYINT(1) NOT NULL DEFAULT 0,
 canAttendInvites1 TINYINT(1) NOT NULL DEFAULT 0,
 canAttendInvites2 TINYINT(1) NOT NULL DEFAULT 0,
 canAttendInvites3 TINYINT(1) NOT NULL DEFAULT 0,
 canAttendInvites4 TINYINT(1) NOT NULL DEFAULT 0,
 canActivateModules1 TINYINT(1) NOT NULL DEFAULT 0,
 canActivateModules2 TINYINT(1) NOT NULL DEFAULT 0,
 canActivateModules3 TINYINT(1) NOT NULL DEFAULT 0,
 canActivateModules4 TINYINT(1) NOT NULL DEFAULT 0,
 canSeeComments1 TINYINT(1) NOT NULL DEFAULT 0,
 canSeeComments2 TINYINT(1) NOT NULL DEFAULT 0,
 canSeeComments3 TINYINT(1) NOT NULL DEFAULT 0,
 canSeeComments4 TINYINT(1) NOT NULL DEFAULT 0,
 canMakeComments1 TINYINT(1) NOT NULL DEFAULT 0,
 canMakeComments2 TINYINT(1) NOT NULL DEFAULT 0,
 canMakeComments3 TINYINT(1) NOT NULL DEFAULT 0,
 canMakeComments4 TINYINT(1) NOT NULL DEFAULT 0,
 canEditComments1 TINYINT(1) NOT NULL DEFAULT 0,
 canEditComments2 TINYINT(1) NOT NULL DEFAULT 0,
 canEditComments3 TINYINT(1) NOT NULL DEFAULT 0,
 canEditComments4 TINYINT(1) NOT NULL DEFAULT 0,
 canDeleteComments1 TINYINT(1) NOT NULL DEFAULT 0,
 canDeleteComments2 TINYINT(1) NOT NULL DEFAULT 0,
 canDeleteComments3 TINYINT(1) NOT NULL DEFAULT 0,
 canDeleteComments4 TINYINT(1) NOT NULL DEFAULT 0,
 UNIQUE KEY cliqueID (cliqueID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS wcf1_clique_visitor;
CREATE TABLE wcf1_clique_visitor (
 cliqueID INT(10) NOT NULL DEFAULT 0,
 userID INT(10) NOT NULL DEFAULT 0,
 time INT(10) NOT NULL DEFAULT 0,
 UNIQUE KEY cliqueID (cliqueID, userID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS wcf1_clique_rating;
CREATE TABLE wcf1_clique_rating (
 cliqueID INT(10) NOT NULL DEFAULT 0,
 userID INT(10) NOT NULL DEFAULT 0,
 rating INT(10) NOT NULL DEFAULT 0,
 UNIQUE KEY cliqueID (cliqueID, userID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS wcf1_clique_invite;
CREATE TABLE wcf1_clique_invite (
 cliqueID INT(10) NOT NULL DEFAULT 0,
 inviterID  INT(10) NOT NULL DEFAULT 0,
 inviteeID INT(10) NOT NULL DEFAULT 0,
 time INT(10) NOT NULL DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS wcf1_clique_application;
CREATE TABLE wcf1_clique_application (
 cliqueID INT(10) NOT NULL DEFAULT 0,
 userID  INT(10) NOT NULL DEFAULT 0,
 message TEXT,
 time INT(10) NOT NULL DEFAULT 0,
 UNIQUE KEY cliqueID (cliqueID, userID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS wcf1_clique_comments;
CREATE TABLE wcf1_clique_comments (
 commentID int(10) NOT NULL AUTO_INCREMENT,
 cliqueID int(10) NOT NULL,
 userID int(10) NOT NULL DEFAULT 0,
 message mediumtext,
 time int(10) NOT NULL DEFAULT 0,
 PRIMARY KEY (commentID),
 KEY cliqueID (cliqueID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=3;

DROP TABLE IF EXISTS wcf1_clique_category;
CREATE TABLE wcf1_clique_category (
 categoryID int(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
 category VARCHAR(255) NOT NULL DEFAULT '',
 showOrder INT(10) NOT NULL DEFAULT 0,
 disabled INT(1) NOT NULL DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS wcf1_clique_menu_item;
CREATE TABLE wcf1_clique_menu_item (
 menuItemID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
 packageID INT(10) NOT NULL DEFAULT 0,
 menuItem VARCHAR(255) NOT NULL DEFAULT '',
 menuItemLink VARCHAR(255) NOT NULL DEFAULT '',
 menuItemIcon VARCHAR(255) NOT NULL DEFAULT '',
 permissions VARCHAR(255) NOT NULL DEFAULT '',
 groupoption VARCHAR(255) NOT NULL DEFAULT '',
 UNIQUE KEY menuItem (menuItem)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;